#!/usr/bin/env ruby

def execute(cmd)
  puts "\n***************************************************************************\n"
  puts "$ #{cmd}"
  system(cmd)
end

def version_file_path
  './lib/will_filter/version.rb'
end

def version_file
  @version_file ||= File.read(version_file_path)
end

def version
  @version ||= version_file.match(/VERSION\s*=\s*'([^']*)'/)[1]
end

def increment_version
  parts = version.split('.')
  parts[2] = (parts[2].to_i + 1).to_s
  new_version = parts.join('.')

  version_file.gsub!(version, new_version)

  File.open(version_file_path, 'w') do |file|
    file.write(version_file)
  end

  @version_file = nil
  @version = nil
end

puts "\nBuilding will_filter-#{version}.gem..."

if ARGV.include?('release')
  execute('git checkout master')
  execute('git merge develop')
  execute('git push')
end

execute('bundle exec rspec')
execute('gem build will_filter.gemspec')
execute("gem install will_filter-#{version}.gem --no-ri --no-rdoc")

if ARGV.include?('release')
  execute("git tag #{version}")
  execute('git push --tags')

  execute("gem push will_filter-#{version}.gem")

  execute('git checkout develop')

  increment_version
  execute("git add #{version_file_path}")
  execute("git commit -m 'Updated version to #{version}'")
  execute('git push')
end



